name: Update transcripts data

on:
  workflow_dispatch:
  schedule:
    - cron: "14 17 * * 0"
    - cron: "33 17 * * 0"
    - cron: "47 17 * * 0"
    - cron: "3 18 * * 0"
    - cron: "5 9 * * 0"
    # Every day at 2:03 AM EST (converted to UTC).
    - cron: "3 7 * * *"
    # Every December 24th at 7:03 & 7:13 PM EST (converted to UTC).
    - cron: "03 0 24 12 *"
    - cron: "13 0 24 12 *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Clone whisper.cpp
        run: git clone https://github.com/ggerganov/whisper.cpp --depth=1

      - name: Cache Whisper.cpp build and model
        uses: actions/cache@v4
        id: whisper-cache
        with:
          path: |
            whisper.cpp
            whisper-cli
            ggml-tiny.en.bin
          key: ${{ runner.os }}-whisper-${{ hashFiles('whisper.cpp/Makefile') }}

      - name: Install necessary tools
        run: |
          curl -L https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-linux64-gpl.tar.xz -o ffmpeg.tar.xz
          tar -xf ffmpeg.tar.xz --strip-components=1 -C /tmp/
          sudo mv /tmp/bin/ffmpeg /usr/local/bin/
          rm ffmpeg.tar.xz
          
          pip install -r data/requirements.txt
          curl -fsSL https://deno.land/install.sh | sh -s -- -y
          echo "$HOME/.deno/bin" >> $GITHUB_PATH

      - name: Build whisper.cpp
        if: steps.whisper-cache.outputs.cache-hit != 'true'
        run: |
          sudo apt install build-essential cmake
          cd whisper.cpp
          make
          ./models/download-ggml-model.sh tiny.en
          mv build/bin/whisper-cli ../whisper-cli
          mv models/ggml-tiny.en.bin ../ggml-tiny.en.bin

      - name: Save cached cookies to a file
        env:
          COOKIES: ${{ secrets.COOKIES }}
        run: echo "$COOKIES" | base64 -d > cookies.txt

      - name: Run python script
        env:
          API_KEY: ${{ secrets.API_KEY }}
          IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
          IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
        run: python3 ./data/update_data.py

      - name: Push files to GitHub
        if: ${{ success() || failure() || cancelled() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "fbcss-deploy[bot]"
          git config --global user.email "fbcss-deploy[bot]@users.noreply.github.com"
          git add data/transcripts.json data/id_map.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated transcription"
            git pull --rebase origin main
            git push -u origin main
          fi
